#!/usr/bin/env python3
"""Deploy MTU only after the change-class behavior gate passes."""
from __future__ import annotations

import argparse
import json
import os
import shutil
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from mtu_eval_policy import (
    DEFAULT_POLICY, canonical_digest, compare_baseline, infer_affected_tags,
    load_policy, parse_time, read_json, sha256_file, validate_report_shape,
)

MTU_ROOT = Path(__file__).resolve().parents[1]


class DeployRefused(RuntimeError):
    pass


def _verify_waiver(path: Path | None) -> dict[str, Any] | None:
    if path is None:
        return None
    waiver = read_json(path)
    if waiver.get("principal") not in {"teren", "amelia"}:
        raise DeployRefused("waiver principal must be teren or amelia")
    if not str(waiver.get("quote") or "").strip():
        raise DeployRefused("waiver must preserve the principal's recorded word")
    if "nightly_red" not in (waiver.get("waives") or []):
        raise DeployRefused("waiver does not name nightly_red")
    parse_time(str(waiver.get("recorded_at") or ""))
    return waiver


def _secret_value(path: Path, key: str) -> str:
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line.startswith("export "):
            line = line[7:].lstrip()
        if line.startswith(key + "="):
            return line.split("=", 1)[1].strip().strip('"').strip("'")
    raise DeployRefused(f"{key} is absent from the secrets store")


def install_runtime(
    *, target_home: Path, token_file: Path, allowed_users: str,
    secrets_file: Path,
) -> None:
    token = "".join(token_file.read_text(encoding="utf-8").split())
    if not token:
        raise DeployRefused("telegram token file is empty")
    openai_key = _secret_value(secrets_file, "OPENAI_API_KEY")
    target_home.mkdir(parents=True, exist_ok=True)
    for name in ("config.yaml", "mtu_constitution.yaml", "SOUL.md"):
        pending = target_home / f".{name}.pending"
        shutil.copy2(MTU_ROOT / name, pending)
        pending.replace(target_home / name)
    env = "\n".join((
        "# hermes-mtu pilot secrets — generated by deploy_guarded.py",
        f"TELEGRAM_BOT_TOKEN={token}",
        f"TELEGRAM_ALLOWED_USERS={allowed_users}",
        f"OPENAI_API_KEY={openai_key}",
        "TELEGRAM_HOME_CHANNEL=" + os.environ.get("TELEGRAM_HOME_CHANNEL", "276672685"),
        "",
    ))
    pending_env = target_home / ".env.pending"
    pending_env.write_text(env, encoding="utf-8")
    pending_env.chmod(0o600)
    pending_env.replace(target_home / ".env")


def _canaries_clean(report: dict[str, Any]) -> bool:
    canaries = [case for case in report.get("cases") or [] if case.get("canary")]
    if not canaries:
        return False
    for case in canaries:
        for turn in case.get("turns") or []:
            for assertion in turn.get("assertions") or []:
                if assertion.get("passed") is False or assertion.get("status") == "pending_judge":
                    return False
    return True


def _judge_matches_pin(report: dict[str, Any], policy: dict[str, Any]) -> bool:
    summary = report.get("judge_summary") or {}
    pin = policy.get("judge") or {}
    return (
        summary.get("status") == "passed"
        and summary.get("model") == pin.get("model")
        and summary.get("reasoning_effort") == pin.get("reasoning_effort")
        and summary.get("schema") == pin.get("schema")
    )


def evaluate_gate(
    *, change_class: str, changed_files: list[str], report: dict[str, Any],
    nightly: dict[str, Any], policy: dict[str, Any], baseline: dict[str, Any],
    waiver: dict[str, Any] | None = None,
) -> dict[str, Any]:
    failures: list[str] = []
    gate = (policy.get("gates") or {}).get(change_class)
    if not gate:
        raise DeployRefused(f"unknown change class: {change_class}")

    max_age = float(policy["nightly"]["maximum_age_hours"])
    try:
        age_hours = (datetime.now(timezone.utc) - parse_time(nightly["recorded_at"])).total_seconds() / 3600
    except Exception:
        age_hours = max_age + 1
    if nightly.get("status") != "green" and waiver is None:
        failures.append("latest nightly is red and has no recorded principal waiver")
    if age_hours > max_age:
        failures.append(f"latest nightly is stale ({age_hours:.1f}h > {max_age:.1f}h)")

    try:
        report_age_hours = (
            datetime.now(timezone.utc) - parse_time(report["generated_at"])
        ).total_seconds() / 3600
    except Exception:
        report_age_hours = max_age + 1
    if report_age_hours > max_age:
        failures.append(f"eval report is stale ({report_age_hours:.1f}h > {max_age:.1f}h)")

    canonical_corpus = read_json(MTU_ROOT / policy["corpus"]["path"])
    if (report.get("corpus") or {}).get("source_digest") != canonical_digest(canonical_corpus):
        failures.append("eval report corpus digest does not match the deploy-tree corpus")
    runtime = (report.get("execution") or {}).get("runtime") or {}
    if runtime.get("source_config_sha256") != sha256_file(MTU_ROOT / "config.yaml"):
        failures.append("eval report config digest does not match the deploy tree")
    if runtime.get("source_constitution_sha256") != sha256_file(MTU_ROOT / "mtu_constitution.yaml"):
        failures.append("eval report constitution digest does not match the deploy tree")
    shape_defects = validate_report_shape(
        report, canonical_corpus, require_judge=bool(gate.get("require_judge"))
    )
    if shape_defects:
        failures.append("eval report is structurally incomplete: " + "; ".join(shape_defects[:5]))

    regression = compare_baseline(
        report, baseline, require_full_corpus=bool(gate.get("require_full_corpus"))
    )
    if regression["status"] != "green":
        failures.append(f"eval has {regression['new_failure_count']} new deterministic failures")

    required_tags = infer_affected_tags(policy, changed_files)
    selected_tags = set((report.get("corpus") or {}).get("tags") or [])
    if gate.get("require_affected_tags"):
        if not required_tags:
            failures.append("changed files have no source-tag mapping")
        elif not required_tags.issubset(selected_tags):
            failures.append("eval report is missing affected tags: " + ", ".join(sorted(required_tags - selected_tags)))
    if gate.get("require_smoke_tags"):
        smoke = set(policy.get("smoke_tags") or [])
        if not smoke.issubset(selected_tags):
            failures.append("eval report is missing smoke tags: " + ", ".join(sorted(smoke - selected_tags)))

    expected_case_ids = {
        str(case["case_id"])
        for case in canonical_corpus.get("cases") or []
        if not selected_tags or selected_tags.intersection(case.get("tags") or [])
    }
    actual_case_ids = {str(case.get("case_id")) for case in report.get("cases") or []}
    missing_selected = sorted(expected_case_ids - actual_case_ids)
    if missing_selected:
        failures.append(
            f"eval report omits {len(missing_selected)} cases selected by its declared tags"
        )

    corpus = report.get("corpus") or {}
    if gate.get("require_full_corpus") and int(corpus.get("selected_case_count") or 0) != int(corpus.get("declared_case_count") or -1):
        failures.append("full corpus was not selected")
    required_draws = int(gate.get("require_draws") or 0)
    if required_draws:
        counts = Counter(str(case.get("case_id")) for case in report.get("cases") or [])
        short = sorted(key for key, count in counts.items() if count < required_draws)
        if short or not counts:
            failures.append(f"full corpus draw floor {required_draws} not met")
    if gate.get("require_live_path") and (report.get("execution") or {}).get("path") != "live_channel_battery":
        failures.append("live channel battery evidence is absent")
    if gate.get("require_judge") and not _judge_matches_pin(report, policy):
        failures.append("semantic judge is not fully passed under the pinned model/schema")
    if gate.get("require_canaries_clean") and not _canaries_clean(report):
        failures.append("canaries are absent, pending, or red")
    validations = report.get("validations") or {}
    if gate.get("require_reference_validation") and validations.get("reference") != "passed":
        failures.append("reference validation is not passed")
    if gate.get("require_document_registration") and validations.get("document_registration") != "passed":
        failures.append("document registration is not passed")

    verdict = {
        "ok": not failures, "change_class": change_class,
        "required_tags": sorted(required_tags), "selected_tags": sorted(selected_tags),
        "regression": regression, "nightly_status": nightly.get("status"),
        "waiver": waiver, "failures": failures,
    }
    if failures:
        raise DeployRefused("; ".join(failures))
    return verdict


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--change-class", required=True, choices=("rule", "reference", "document", "model", "provider", "channel", "debut"))
    parser.add_argument("--changed-file", action="append", default=[])
    parser.add_argument("--report", required=True, type=Path)
    parser.add_argument("--nightly", type=Path)
    parser.add_argument("--policy", type=Path, default=DEFAULT_POLICY)
    parser.add_argument("--waiver", type=Path)
    parser.add_argument("--check-only", action="store_true")
    parser.add_argument("--target-home", type=Path, default=Path.home() / ".hermes-mtu")
    parser.add_argument("--token-file", type=Path)
    parser.add_argument("--allowed-users")
    args = parser.parse_args()
    policy = load_policy(args.policy)
    nightly_path = args.nightly or Path(policy["nightly"]["state_dir"]).expanduser() / "latest.json"
    baseline = read_json((args.policy.parent / policy["corpus"]["accepted_baseline"]).resolve())
    waiver = _verify_waiver(args.waiver)
    try:
        verdict = evaluate_gate(
            change_class=args.change_class, changed_files=args.changed_file,
            report=read_json(args.report), nightly=read_json(nightly_path),
            policy=policy, baseline=baseline, waiver=waiver,
        )
    except DeployRefused as exc:
        print(json.dumps({"ok": False, "code": "MTU_DEPLOY_EVAL_REFUSED", "error": str(exc)}, sort_keys=True))
        raise SystemExit(2)
    if args.check_only:
        print(json.dumps({"ok": True, "deployed": False, "gate": verdict}, sort_keys=True))
        return
    if not args.token_file or args.allowed_users is None:
        raise SystemExit("deployment requires --token-file and --allowed-users")
    install_runtime(
        target_home=args.target_home.expanduser().resolve(),
        token_file=args.token_file.expanduser().resolve(),
        allowed_users=args.allowed_users,
        secrets_file=Path.home() / ".marshal/secrets.env",
    )
    print(json.dumps({"ok": True, "deployed": True, "target_home": str(args.target_home), "gate": verdict}, sort_keys=True))


if __name__ == "__main__":
    main()
